// Generated by using torchexport::export() -> do not edit by hand
#include "lltm/lltm.h"
#include <lantern/types.h>

void * p_lltm_last_error = NULL;

LLTM_API void* lltm_last_error()
{
  return p_lltm_last_error;
}

LLTM_API void lltm_last_error_clear()
{
  p_lltm_last_error = NULL;
}

torch::Tensor contrarian (torch::Tensor z);
LLTM_API void* _contrarian (void* z) {
  try {
    return  make_raw::Tensor(contrarian(from_raw::Tensor(z)));
  } LLTM_HANDLE_EXCEPTION
  return (void*) NULL;
}
