# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_contrarian <- function(z) {
    .Call('_lltm_rcpp_contrarian', PACKAGE = 'lltm', z)
}

cpp_jit_get_all_operators_names <- function() {
    .Call('_lltm_cpp_jit_get_all_operators_names', PACKAGE = 'lltm')
}

cpp_jit_get_operator_from_name <- function(x) {
    .Call('_lltm_cpp_jit_get_operator_from_name', PACKAGE = 'lltm', x)
}

cpp_jit_get_all_operators_for <- function(x) {
    .Call('_lltm_cpp_jit_get_all_operators_for', PACKAGE = 'lltm', x)
}

lltm_raise_exception <- function() {
    invisible(.Call('_lltm_lltm_raise_exception', PACKAGE = 'lltm'))
}

